---
- name: Create k3s-master systemd service
  become: true
  template:
    src: "k3s-master.service.j2"
    dest: "/etc/systemd/system/k3s-master.service"
  notify: "restart k3s-master"

- name: Make sure k3s-master is running
  systemd:
    name: "k3s-master.service"
    state: started
    enabled: true
    daemon_reload: true
