---

- name: Create k3s-node systemd service
  become: true
  template:
    src: "k3s-node.service.j2"
    dest: "/etc/systemd/system/k3s-node.service"
  notify: "restart k3s-node"

- name: Make sure k3s-node is running
  systemd:
    name: "k3s-node.service"
    state: started
    enabled: true
    daemon_reload: true
