---
- name: restart k3s-master
  systemd:
    name: "k3s-master.service"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart k3s-node
  systemd:
    name: "k3s-node.service"
    state: restarted
    enabled: yes
    daemon_reload: yes
