---

- name: "Set default rules"
  iptables_raw:
    name: default_rules
    weight: 10
    keep_unmanaged: yes
    rules: "{{ iptables_default_rules }}"

- name: "Set rules"
  iptables_raw:
    name: "{{ item.name }}"
    weight: "{{ item.weight }}"
    keep_unmanaged: "{{ item.keep_unmanaged }}"
    rules: "{{ item.rules }}"
  loop: "{{ iptables_rules }}"

- name: "Set table rules"
  iptables_raw:
    name: "{{ item.name }}"
    weight: "{{ item.weight }}"
    keep_unmanaged: "{{ item.keep_unmanaged }}"
    table: "{{ item.table }}"
    rules: "{{ item.rules }}"
  loop: "{{ iptables_table_rules }}"
