---

- name: "change hostname"
  hostname:
    name: "{{ inventory_hostname }}"
  notify: "reboot"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 localhost {{ inventory_hostname }}'
    state: present
  notify: "reboot"

- name: "reboot if necessary"
  meta: "flush_handlers"
