---

- name: "Update cache and upgrade package(s) (pacman -Syu)"
  pacman:
    update_cache: yes
    upgrade: yes
  register: "upgrade"

- name: "Upgraded package(s)"
  debug:
      msg: "{{ upgrade.packages }}"

- name: "Install package"
  pacman:
    name: "{{ packages }}"
    state: "present"
    update_cache: yes

- name: "Remove package"
  pacman:
    name: "{{ packages_toremove }}"
    state: "absent"

- name: "Reboot needed after kernel upgrade"
  reboot:
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: "whoami"
  when: "'linux' in upgrade.packages"
