---

- name: "create metrics.sh"
  template:
      src: "metrics.sh.j2"
      dest: "/usr/bin/metrics.sh"
      owner: "root"
      group: "root"
      mode: +x

- name: "create systemd service"
  template:
      src: "metrics.service.j2"
      dest: "/etc/systemd/system/metrics.service"
      owner: "root"
      group: "root"
  notify: "pushmetrics-restart-timer"

- name: "create systemd timer"
  template:
      src: "metrics.timer.j2"
      dest: "/etc/systemd/system/metrics.timer"
      owner: "root"
      group: "root"
  notify: "pushmetrics-restart-service"
