---

- name: "pushmetrics-restart-timer"
  systemd:
      daemon_reload: yes
      enabled: yes
      name: metrics.timer
      state: restarted

- name: "pushmetrics-restart-service"
  systemd:
      daemon_reload: yes
      enabled: yes
      name: metrics.service
      state: restarted
