---

- name: "Install docker"
  pacman:
    name:
        - "docker"
        - "docker-compose"
        - "python-docker"
    state: latest

- name: "Create /etc/systemd/system/docker.service.d"
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    mode: 0750

- name: "Create /etc/systemd/system/docker.service.d/docker.conf"
  template:
    src: "docker.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/docker.conf"
    owner: root
    group: root
    mode: 0640
  register: "dockerconf"

- name: "Systemd daemon reload"
  systemd:
    name: "docker"
    state: restarted
    daemon_reload: yes
  when: dockerconf.changed

- name: "Enable and start docker"
  systemd:
    name: "docker"
    state: started
    enabled: yes
