---

- name: "pushmetrics-custom-restart-timer"
  systemd:
      daemon_reload: yes
      enabled: yes
      name: "metrics-{{ pushgateway_custom_job_name }}.timer"
      state: restarted

- name: "pushmetrics-custom-restart-service"
  systemd:
      daemon_reload: yes
      enabled: yes
      name: "metrics-{{ pushgateway_custom_job_name }}.service"
      state: restarted
