---

#- name: "Stop existing service if installed by package"
#  systemd:
#      name: "prometheus-node-exporter"
#      state: "stopped"

- include: "{{ ansible_distribution }}.yml"

- name: "Download and extract {{ node_exporter_url }}"
  unarchive:
    src: "{{ node_exporter_url }}"
    dest: "/tmp"
    remote_src: yes

- name: "Install binary"
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version_arch }}/node_exporter"
    dest: "/usr/bin/node_exporter"
    owner: "root"
    group: "root"
    mode: '0755'
    remote_src: "yes"
  notify: "restart-node-exporter"

- name: "Copy the Node Exporter systemd service file"
  template:
    src: "node-exporter.service.j2"
    dest: "/etc/systemd/system/node-exporter.service"
    owner: "root"
    group: "root"
    mode: '0644'
  notify: "restart-node-exporter"

- name: "Make sure node-exporter is running"
  systemd:
    state: "started"
    name: "node-exporter"
